import os
import uuid
import json
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

# ── Load environment variables from .env file ──────────────────────────
load_dotenv()

# ── Create the Flask app ───────────────────────────────────────────────
app = Flask(__name__)

# ── Set up rate limiting ───────────────────────────────────────────────
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Set up Groq client ─────────────────────────────────────────────────
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# ── Audit log storage (in memory for now) ─────────────────────────────
audit_log = []

# ── Content storage (tracks status of each submission) ────────────────
content_store = {}


# ══════════════════════════════════════════════════════════════════════
#  SIGNAL 1: LLM-Based Classification via Groq
# ══════════════════════════════════════════════════════════════════════

def get_llm_score(text):
    """
    Sends the text to Groq and asks it to score how likely
    the text is AI-generated. Returns a float between 0 and 1.
    1.0 = very likely AI-generated
    0.0 = very likely human-written
    """

    prompt = f"""You are an expert at detecting whether text was written by a human or generated by AI.

Analyze the following text and return ONLY a single number between 0.0 and 1.0.
- 0.0 means you are certain it was written by a human
- 1.0 means you are certain it was generated by AI
- Use values in between to express uncertainty

Do not explain your reasoning. Do not include any other text. Just the number.

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )

    raw = response.choices[0].message.content.strip()

    # Convert the response to a float, clamp between 0 and 1
    score = float(raw)
    score = max(0.0, min(1.0, score))
    return score


# ══════════════════════════════════════════════════════════════════════
#  SIGNAL 2: Stylometric Heuristics
# ══════════════════════════════════════════════════════════════════════

def get_stylometric_score(text):
    """
    Analyzes the writing style using measurable statistics.
    AI text tends to be uniform; human text tends to be more variable.
    Returns a float between 0 and 1.
    1.0 = very likely AI-generated
    0.0 = very likely human-written
    """

    sentences = [s.strip() for s in text.replace("!", ".").replace("?", ".").split(".") if s.strip()]

    if len(sentences) < 2:
        return 0.5  # Not enough text to analyze, return neutral

    # ── Metric 1: Sentence length variance ────────────────────────────
    # Human writing has more varied sentence lengths
    lengths = [len(s.split()) for s in sentences]
    avg_length = sum(lengths) / len(lengths)
    variance = sum((l - avg_length) ** 2 for l in lengths) / len(lengths)

    # Low variance = more uniform = more AI-like
    # We normalize: variance of 0 → score 1.0, variance of 50+ → score 0.0
    variance_score = max(0.0, 1.0 - (variance / 50.0))

    # ── Metric 2: Type-token ratio (vocabulary diversity) ─────────────
    # Human writing uses more varied vocabulary
    words = text.lower().split()
    if len(words) == 0:
        ttr_score = 0.5
    else:
        unique_words = set(words)
        ttr = len(unique_words) / len(words)
        # High TTR = more diverse = more human-like
        # Low TTR = repetitive = more AI-like
        ttr_score = max(0.0, 1.0 - ttr)

    # ── Metric 3: Punctuation density ─────────────────────────────────
    # AI text often uses punctuation more consistently
    punctuation_chars = sum(1 for c in text if c in ",.;:!?")
    punct_density = punctuation_chars / max(len(text), 1)

    # Higher punctuation density = more AI-like (normalized to 0–1)
    punct_score = min(1.0, punct_density * 20)

    # ── Combine the three metrics equally ─────────────────────────────
    combined = (variance_score + ttr_score + punct_score) / 3
    return round(combined, 4)


# ══════════════════════════════════════════════════════════════════════
#  CONFIDENCE SCORING
# ══════════════════════════════════════════════════════════════════════

def get_confidence_score(llm_score, stylometric_score):
    """
    Combines both signal scores into one confidence score.
    Groq (LLM) gets 60% weight, stylometrics get 40%.
    Returns a float between 0 and 1.
    """
    return round((llm_score * 0.6) + (stylometric_score * 0.4), 4)


# ══════════════════════════════════════════════════════════════════════
#  TRANSPARENCY LABEL
# ══════════════════════════════════════════════════════════════════════

def get_label(confidence):
    """
    Maps a confidence score to one of three label variants.
    """
    if confidence >= 0.65:
        attribution = "likely_ai"
        label = (
            "⚠️ Our system found patterns consistent with AI-generated text. "
            "This content has been flagged for review. If you are the creator "
            "and believe this is an error, you may submit an appeal."
        )
    elif confidence >= 0.36:
        attribution = "uncertain"
        label = (
            "🔍 Our system could not confidently determine whether this content "
            "was human-written or AI-generated. It has been marked as uncertain. "
            "Creators may submit an appeal to provide additional context."
        )
    else:
        attribution = "likely_human"
        label = (
            "✅ Our system found patterns consistent with human-written content. "
            "This content has been attributed to the creator."
        )
    return attribution, label


# ══════════════════════════════════════════════════════════════════════
#  AUDIT LOG HELPER
# ══════════════════════════════════════════════════════════════════════

def write_log_entry(entry):
    """Appends a structured entry to the in-memory audit log."""
    audit_log.append(entry)


# ══════════════════════════════════════════════════════════════════════
#  ROUTES
# ══════════════════════════════════════════════════════════════════════

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    """
    Accepts a piece of text for attribution analysis.
    Returns: content_id, attribution, confidence, label
    """
    data = request.get_json()

    # Validate that required fields are present
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = data["text"]
    creator_id = data["creator_id"]

    # Generate a unique ID for this submission
    content_id = str(uuid.uuid4())

    # Run both detection signals
    llm_score = get_llm_score(text)
    stylometric_score = get_stylometric_score(text)

    # Combine into one confidence score
    confidence = get_confidence_score(llm_score, stylometric_score)

    # Generate the transparency label
    attribution, label = get_label(confidence)

    # Save to content store so appeals can look it up
    content_store[content_id] = {
        "content_id": content_id,
        "creator_id": creator_id,
        "text": text,
        "attribution": attribution,
        "confidence": confidence,
        "status": "classified",
    }

    # Write to audit log
    write_log_entry({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "status": "classified",
        "appeal_reasoning": None,
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    """
    Accepts an appeal from a creator who believes they were misclassified.
    Requires: content_id, creator_reasoning
    """
    data = request.get_json()

    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    # Check that this content_id exists
    if content_id not in content_store:
        return jsonify({"error": "content_id not found"}), 404

    # Update the status in content store
    content_store[content_id]["status"] = "under_review"

    # Find the original log entry and update it
    for entry in audit_log:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"
            entry["appeal_reasoning"] = reasoning
            break

    return jsonify({
        "message": "Appeal received. Your content has been marked as under review.",
        "content_id": content_id,
    })


@app.route("/log", methods=["GET"])
def get_log():
    """Returns all audit log entries as JSON."""
    return jsonify({"entries": audit_log})


# ══════════════════════════════════════════════════════════════════════
#  RUN THE APP
# ══════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    app.run(debug=True)