# detection.py
# ─────────────────────────────────────────────────────────────
# This file handles everything related to analyzing text.
# It does not know about Flask or routes at all.
# It contains:
#   - Signal 1: LLM-based classification via Groq
#   - Signal 2: Stylometric heuristics
#   - Confidence scoring (combines both signals)
#   - Label generation (turns a score into plain English)
# ─────────────────────────────────────────────────────────────

import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

# Set up the Groq client once when this file is imported
client = Groq(api_key=os.getenv("GROQ_API_KEY"))


# ══════════════════════════════════════════════════════════════
#  SIGNAL 1: LLM-Based Classification via Groq
# ══════════════════════════════════════════════════════════════

def get_llm_score(text):
    """
    Sends the text to Groq and asks it to score how likely
    the text is AI-generated.

    Returns a float between 0 and 1.
    1.0 = very likely AI-generated
    0.0 = very likely human-written
    """

    prompt = f"""You are an expert at detecting whether text was written 
by a human or generated by AI.

Analyze the following text and return ONLY a single number between 
0.0 and 1.0.
- 0.0 means you are certain it was written by a human
- 1.0 means you are certain it was generated by AI
- Use values in between to express uncertainty

Do not explain your reasoning. Do not include any other text. 
Just the number.

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )

    raw = response.choices[0].message.content.strip()

    # Convert to float and clamp between 0 and 1
    score = float(raw)
    score = max(0.0, min(1.0, score))
    return score


# ══════════════════════════════════════════════════════════════
#  SIGNAL 2: Stylometric Heuristics
# ══════════════════════════════════════════════════════════════

def get_stylometric_score(text):
    """
    Analyzes writing style using measurable statistics.
    AI text tends to be uniform; human text more variable.

    Returns a float between 0 and 1.
    1.0 = very likely AI-generated
    0.0 = very likely human-written
    """

    sentences = [
        s.strip()
        for s in text.replace("!", ".").replace("?", ".").split(".")
        if s.strip()
    ]

    # Not enough text to analyze — return neutral score
    if len(sentences) < 2:
        return 0.5

    # ── Metric 1: Sentence length variance ────────────────────
    # Human writing has more varied sentence lengths.
    # Low variance = uniform = more AI-like.
    lengths = [len(s.split()) for s in sentences]
    avg_length = sum(lengths) / len(lengths)
    variance = sum((l - avg_length) ** 2 for l in lengths) / len(lengths)
    variance_score = max(0.0, 1.0 - (variance / 50.0))

    # ── Metric 2: Type-token ratio (vocabulary diversity) ─────
    # Human writing uses more varied vocabulary.
    # Low TTR = repetitive = more AI-like.
    words = text.lower().split()
    if len(words) == 0:
        ttr_score = 0.5
    else:
        unique_words = set(words)
        ttr = len(unique_words) / len(words)
        ttr_score = max(0.0, 1.0 - ttr)

    # ── Metric 3: Punctuation density ─────────────────────────
    # AI text often uses punctuation more consistently.
    punctuation_chars = sum(1 for c in text if c in ",.;:!?")
    punct_density = punctuation_chars / max(len(text), 1)
    punct_score = min(1.0, punct_density * 20)

    # ── Combine the three metrics equally ─────────────────────
    combined = (variance_score + ttr_score + punct_score) / 3
    return round(combined, 4)


# ══════════════════════════════════════════════════════════════
#  CONFIDENCE SCORING
# ══════════════════════════════════════════════════════════════

def get_confidence_score(llm_score, stylometric_score):
    """
    Combines both signal scores into one confidence score.
    Groq gets 60% weight, stylometrics get 40%.

    Returns a float between 0 and 1.
    """
    return round((llm_score * 0.6) + (stylometric_score * 0.4), 4)


# ══════════════════════════════════════════════════════════════
#  TRANSPARENCY LABEL
# ══════════════════════════════════════════════════════════════

def get_label(confidence):
    """
    Maps a confidence score to one of three label variants.

    Returns a tuple: (attribution string, label text)
    """
    if confidence >= 0.65:
        attribution = "likely_ai"
        label = (
            "⚠️ Our system found patterns consistent with AI-generated text. "
            "This content has been flagged for review. If you are the creator "
            "and believe this is an error, you may submit an appeal."
        )
    elif confidence >= 0.36:
        attribution = "uncertain"
        label = (
            "🔍 Our system could not confidently determine whether this content "
            "was human-written or AI-generated. It has been marked as uncertain. "
            "Creators may submit an appeal to provide additional context."
        )
    else:
        attribution = "likely_human"
        label = (
            "✅ Our system found patterns consistent with human-written content. "
            "This content has been attributed to the creator."
        )
    return attribution, label